package vistas;

import modelos.Asignatura;

/**
 *
 * @author Naomi
 */
public class JFrmMaestYMater extends javax.swing.JFrame {
    
    private static int tipoVentana;
    private static int noMaestro;
    
    public static int getNoMAestro(){
        if(noMaestro==0){
            return noMaestro;
        }else{
            return noMaestro-1;
        }
    }
    
    public static void setNoMaestro(int no){
        noMaestro = no;
    }

    public static int getTipoVentana() {
        return tipoVentana;
    }

    public static void setTipoVentana(int tipoVentana) {
        JFrmMaestYMater.tipoVentana = tipoVentana;
    }
    
    /**
     * Creates new form JFrmShowTeachers
     */
    public JFrmMaestYMater() {
        initComponents();
        setLocationRelativeTo(null);
        this.inicializarTextArea();
    }
    
    private void inicializarTextArea(){
        if (tipoVentana == 0) {
            int y = 0;
            for (int x = 0; x < JFrmStart.getListMaestros().size(); x++) {
                y = x + 1;
                this.textAreaShowTeacher.append(y + ". "
                        + JFrmStart.getListMaestros().get(x).getName()
                        + " " + JFrmStart.getListMaestros().get(x).getApellidoP() + "\n");
            }
        } else {
            
            int b = 0;
            for(int a=0;a<JFrmStart.getListMaterias().size();a++){
                b = a;
                if(JFrmStart.getListMaterias().get(a).isHaveTeacher()){
                    this.textAreaShowTeacher.append( b + ". " 
                            + JFrmStart.getListMaterias().get(a).getNombreAsignatura() + "\n");
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textAreaShowTeacher = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();
        textNumMaestro = new javax.swing.JTextField();
        buttonTerminar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textAreaShowTeacher.setColumns(20);
        textAreaShowTeacher.setRows(5);
        jScrollPane1.setViewportView(textAreaShowTeacher);

        jLabel1.setText("Seleccione el numero de maestro ");

        buttonTerminar.setText("Terminar");
        buttonTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTerminarMouseClicked(evt);
            }
        });

        jLabel2.setText("o de asignatura que desea:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(buttonTerminar)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel2)))
                                .addGap(34, 34, 34))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(textNumMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(textNumMaestro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(buttonTerminar)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonTerminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTerminarMouseClicked
        
        noMaestro = Integer.parseInt(this.textNumMaestro.getText());
        if (tipoVentana == 0) {
            JFrmStart.getListMaterias().get(JFrmUnirMaestros.getIndice()).setHaveTeacher(true);
            JFrmStart.getListMaterias().get(JFrmUnirMaestros.getIndice()).setEducador(JFrmStart.getListMaestros().get(JFrmUnirMaestros.getIndice()));
            this.dispose();
            new JFrmUnirMaestros().setVisible(true);
            
        } else {
            
            Asignatura[] listaMaterias = JFrmStart.getListAlumnos().get(JFrmUnirAlumnos.getIndice()).getListaMaterias();
            listaMaterias[(listaMaterias.length)+1] = JFrmStart.getListMaterias().get(Integer.parseInt(this.textNumMaestro.getText()));
            JFrmStart.getListAlumnos().get(JFrmUnirAlumnos.getIndice()).setListaMaterias(listaMaterias);
            this.dispose();
            new JFrmUnirAlumnos().setVisible(true);
        }
    }//GEN-LAST:event_buttonTerminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmMaestYMater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmMaestYMater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmMaestYMater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmMaestYMater.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmMaestYMater().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea textAreaShowTeacher;
    private javax.swing.JTextField textNumMaestro;
    // End of variables declaration//GEN-END:variables
}
