package vistas;

import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import modelos.Alumno;
import modelos.Asignatura;
import modelos.Maestro;
import modelos.readCsv;

/**
 *
 * @author Naomi
 */
public class JFrmStart extends javax.swing.JFrame {
    
    private static ArrayList<Alumno> listAlumnos;
    private static ArrayList<Asignatura> listMaterias;
    private static ArrayList<Maestro> listMaestros;

    public static ArrayList<Alumno> getListAlumnos() {
        return listAlumnos;
    }

    public static ArrayList<Asignatura> getListMaterias() {
        return listMaterias;
    }

    public static ArrayList<Maestro> getListMaestros() {
        return listMaestros;
    }

    /**
     * Creates new form JFrmStart
     */
    public JFrmStart() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new javax.swing.JLabel();
        label2 = new javax.swing.JLabel();
        label3 = new javax.swing.JLabel();
        label4 = new javax.swing.JLabel();
        jTextCsvAlumnos = new javax.swing.JTextField();
        jTextCsvMaestros = new javax.swing.JTextField();
        jTextMaterias = new javax.swing.JTextField();
        jButtonCargarArchivos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        label1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        label1.setText("Ingrese la ruta del archivo csv.");

        label2.setText("CSV de Alumnos:");

        label3.setText("CSV de Maestros:");

        label4.setText("CSV de Asignaturas:");

        jButtonCargarArchivos.setBackground(new java.awt.Color(0, 51, 153));
        jButtonCargarArchivos.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButtonCargarArchivos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonCargarArchivos.setText("Cargar Archivos");
        jButtonCargarArchivos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonCargarArchivosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(label1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(label3)
                                            .addComponent(label2))
                                        .addGap(29, 29, 29)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jTextCsvAlumnos, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                                            .addComponent(jTextCsvMaestros)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(label4)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButtonCargarArchivos)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(label1)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextCsvAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label2))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextCsvMaestros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(label4)
                    .addComponent(jTextMaterias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButtonCargarArchivos)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCargarArchivosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonCargarArchivosMouseClicked
       
       try {
            readCsv leerAlumnos = new readCsv(this.jTextCsvAlumnos.getText());
            String[][] infoAlum = leerAlumnos.leeCsv();
            agregarAlumnos(infoAlum);
            
            readCsv leerProfes = new readCsv(this.jTextCsvMaestros.getText());
            String[][] infoProfes = leerProfes.leeCsv();
            agregarMaestros(infoProfes);
            
            readCsv leerMaterias = new readCsv(this.jTextMaterias.getText());
            String[][] infoMaterias = leerMaterias.leeCsv();
            agregarAsignaturas(infoMaterias);
            
        } catch (IOException ex) {
            Logger.getLogger(JFrmStart.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        this.dispose();
       new JFrmUnirMaestros().setVisible(true); 
    }//GEN-LAST:event_jButtonCargarArchivosMouseClicked

    private void agregarAlumnos(String[][] infoAlum){
        
        listAlumnos = new ArrayList<>();
        for(int x=0;x<infoAlum.length;x++){
            listAlumnos.add(new Alumno(infoAlum[x][0],infoAlum[x][4],infoAlum[x][3],infoAlum[x][1],infoAlum[x][2]));
        }
    }
    
    private void agregarMaestros(String[][] infoProfes){
        
        listMaestros = new ArrayList<>();
        for(int x=0;x<infoProfes.length;x++){
            listMaestros.add(new Maestro(infoProfes[x][0],infoProfes[x][3],infoProfes[x][1],infoProfes[x][2]));
        }
    }
    
    private void agregarAsignaturas(String[][] infoMaterias){
        
        listMaterias = new ArrayList<>();
        for(int x=0;x<infoMaterias.length;x++){
            listMaterias.add(new Asignatura(infoMaterias[x][0],infoMaterias[x][1],infoMaterias[x][2]));
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmStart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmStart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCargarArchivos;
    private javax.swing.JTextField jTextCsvAlumnos;
    private javax.swing.JTextField jTextCsvMaestros;
    private javax.swing.JTextField jTextMaterias;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    // End of variables declaration//GEN-END:variables
}
