package vistas;

import java.awt.Point;
import modelos.Asignatura;
import modelos.CsvAlumnos;
import modelos.CsvMaestros;
import modelos.GenCSV;
import tablas.AlumnoftMateria;

/**
 *
 * @author Naomi
 */
public class JFrmUnirAlumnos extends javax.swing.JFrame {

    private AlumnoftMateria datos;
    private static int indice;
    
    public static int getIndice(){
        return indice;
    }
    
    /**
     * Creates new form JFrmShowMaterias
     */
    public JFrmUnirAlumnos() {
        initComponents();
        setLocationRelativeTo(null);
        this.incializarTabla();
    }

    private void incializarTabla(){
        datos = new AlumnoftMateria();
        datos.tablaMaestroMateria(tableVerAlumnos);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableVerAlumnos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        buttonTerminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Haga doble clic junto al nombre del alumno");

        tableVerAlumnos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableVerAlumnos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tableVerAlumnosMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(tableVerAlumnos);

        jLabel2.setText("para cargar una asignatura");

        buttonTerminar.setText("Terminar Registro");
        buttonTerminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonTerminarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(49, 49, 49))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(buttonTerminar)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel2)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(10, 10, 10)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(buttonTerminar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tableVerAlumnosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableVerAlumnosMousePressed
       
        if (evt.getClickCount() == 2) {
            Point point = evt.getPoint();
            int row = tableVerAlumnos.rowAtPoint(point);//fila y posisición en el Array
            int column = tableVerAlumnos.columnAtPoint(point);//columna
            indice = row;
            this.dispose();
            JFrmMaestYMater.setTipoVentana(1);
            new JFrmMaestYMater().setVisible(true);
        }
    }//GEN-LAST:event_tableVerAlumnosMousePressed

    private void buttonTerminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonTerminarMouseClicked
         GenCSV csvAlumnos = new CsvAlumnos();
        
        String[][] info;
        
        info = new String[JFrmStart.getListAlumnos().size()][];
        
        for(int a=0;a<JFrmStart.getListAlumnos().size();a++){
            
            Asignatura[] materias = JFrmStart.getListAlumnos().get(a).getListaMaterias();
            
            info[a][0] = JFrmStart.getListAlumnos().get(a).getName() + " lleva la materia de "
                    + materias[0];
        }
        
        csvAlumnos.generaCSV(info);
    }//GEN-LAST:event_buttonTerminarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmUnirAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmUnirAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmUnirAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmUnirAlumnos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmUnirAlumnos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonTerminar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableVerAlumnos;
    // End of variables declaration//GEN-END:variables
}
